name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint
        run: |
          echo "::add-matcher::.github/workflows/flake8-problem-matcher.json"
          flake8 .
